### ISSUE TITLE
NameError: global name 'keychainservice' is not defined

### ISSUE THREAD

**Issue by evgeniy-khatko** [bdelliott/sshpass#1]
$ sshpass login@host
password: 
Connecting to login@host
Sending password
Waiting for $ shell prompt terminator to confirm login...
Traceback (most recent call last):
  File "/usr/local/bin/sshpass", line 94, in <module>
    ssh(username, host, port=int(opts.port), keychainservice=opts.keychainservice)
  File "/usr/local/bin/sshpass", line 68, in ssh
    setpassword(keychainservice, username, password)
  File "/usr/local/bin/sshpass", line 37, in setpassword
    print "Successful login - saving password for user %s under keychain service '%s'" % (username, keychainservice)
NameError: global name 'keychainservice' is not defined
# what should I do to make it work?

**Comment by oliveagle** [comment]
fixed in my fork.
